config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users

	resources :decks do
		collection do
			get "/:id/study" => 'decks#study', as: 'study'
			get "/:id/is_correct" => 'decks#is_correct', as: 'is_correct'
		end
	end

	root 'pages#home'

	resources :flashcards do
		collection do
			get 'study'
			get 'is_correct'
		end
	end

	get "/fetch_card" => 'flashcards#fetch', as: 'fetch_card'

	controller :pages do
		get :home
		get :about
		get :contact
	end
end

app/models/flashcard.rb
class Flashcard < ApplicationRecord
end

app/controllers/flashcards_controller.rb
class FlashcardsController < ApplicationController
  before_action :set_flashcard, only: [:show, :edit, :update, :destroy]

	def study
		@@incrementer = 0
		@flashcards = Flashcard.all
		@currcard = @flashcards[@@incrementer]

	end

	def is_correct
		@flashcards = Flashcard.all

	end

	def fetch
		@flashcards = Flashcard.all
		@@incrementer+=1
		@newcard = @flashcards[@@incrementer]
		puts @@incrementer
		respond_to do |format|
			format.js
		end
		puts @newcard.meaning
	end

  # GET /flashcards
  # GET /flashcards.json
  def index
    @flashcards = Flashcard.all
  end

  # GET /flashcards/1
  # GET /flashcards/1.json
  def show
  end

  # GET /flashcards/new
  def new
    @flashcard = Flashcard.new
  end

  # GET /flashcards/1/edit
  def edit
  end

  # POST /flashcards
  # POST /flashcards.json
  def create
    @flashcard = Flashcard.new(flashcard_params)

    respond_to do |format|
      if @flashcard.save
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully created.' }
        format.json { render :show, status: :created, location: @flashcard }
      else
        format.html { render :new }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /flas:cardtype:cardtypehcards/1
  # PATCH/PUT /flashcards/1.json
  def update
    respond_to do |format|
      if @flashcard.update(flashcard_params)
        format.html { redirect_to @flashcard, notice: 'Flashcard was successfully updated.' }
        format.json { render :show, status: :ok, location: @flashcard }
      else
        format.html { render :edit }
        format.json { render json: @flashcard.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /flashcards/1
  # DELETE /flashcards/1.json
  def destroy
    @flashcard.destroy
    respond_to do |format|
      format.html { redirect_to flashcards_url, notice: 'Flashcard was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_flashcard
      @flashcard = Flashcard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def flashcard_params
      params.require(:flashcard).permit(:data, :meaning, :reading, :kunreading, :onreading, :syn, :tos, :meaningmem, :readingmem, :srslevel, :cardtype, :card_id, :user_id)
    end
end

app/helpers/flashcards_helper.rb
module FlashcardsHelper
end

app/views/flashcards/_card.html.erb
<div id="card">
	<% if currcard.user_id == current_user.id %>
		<div class="column has-text-centered">
			<p><%= currcard.data %></p>
			<p><%= puts currcard.data %></p>
			<br>
			<%= form_with url: is_correct_flashcards_path, local: true, method: 'get' do |f| %>
			<%= f.text_field :value, :class => "input", placeholder: "Meaning" %>
			<p><br></p>
			<%= f.submit "Check", :class => "button is-primary" %>
			<% end %>



			<div class="column has-text-centered">
				<% if @answered %>
					<% if currcard.cardtype == "true" %>
					<p>Correct!</p>
					<% currcard.cardtype = "false" %>
					<% else %>
					<p>False!</p>
					<% end %>
					<% @answered = false %>
					<%= link_to "Next", fetch_card_path, :remote => true %>
				<% end %>
			</div>
		</div>
	<% end %>
</div>

app/views/flashcards/_form.html.erb
<%= simple_form_for(@flashcard) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :data %>
    <%= f.input :meaning %>
    <%= f.input :reading %>
    <%= f.input :kunreading %>
    <%= f.input :onreading %>
    <%= f.input :syn %>
    <%= f.input :tos %>
    <%= f.input :meaningmem %>
    <%= f.input :readingmem %>
    <%= f.input :srslevel %>
    <%= f.input :cardtype %>
    <%= f.input :user_id, :input_html => { :value => "#{current_user.id}" } %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/flashcards/edit.html.erb
<h1>Editing Flashcard</h1>

<%= render 'form', flashcard: @flashcard %>

<%= link_to 'Show', @flashcard %> |
<%= link_to 'Back', flashcards_path %>

app/views/flashcards/fetch.js.erb
$("#newcard").html("<%= escape_javascript(render partial: 'card', locals: { currcard: @newcard } ) %>");

app/views/flashcards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Flashcards</h1>

<table class="table is-striped is-hoverable table center">
  <thead>
    <tr>
      <th>Data</th>
      <th>Meaning</th>
      <th>Reading</th>
      <th>Kunreading</th>
      <th>Onreading</th>
      <th>Syn</th>
      <th>Tos</th>
      <th>Meaningmem</th>
      <th>Readingmem</th>
      <th>Srslevel</th>
      <th>Cardtype</th>
			<th>CardID</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @flashcards.each do |flashcard| %>
      <tr>
        <td><%= flashcard.data %></td>
        <td><%= flashcard.meaning %></td>
        <td><%= flashcard.reading %></td>
        <td><%= flashcard.kunreading %></td>
        <td><%= flashcard.onreading %></td>
        <td><%= flashcard.syn %></td>
        <td><%= flashcard.tos %></td>
        <td><%= flashcard.meaningmem %></td>
        <td><%= flashcard.readingmem %></td>
        <td><%= flashcard.srslevel %></td>
        <td><%= flashcard.cardtype %></td>
				<td><%= flashcard.card_id %></td>
        <td><%= flashcard.user_id %></td>
        <td><%= link_to 'Show', flashcard %></td>
        <td><%= link_to 'Edit', edit_flashcard_path(flashcard) %></td>
        <td><%= link_to 'Destroy', flashcard, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Flashcard', new_flashcard_path %>
<div>
	<%= link_to 'Back', "home", class: "button is-danger" %>
</div>


<!--

TODO: add way for cards to be divided into learning session decks
IDEA: put form inside loop, so the answer is sent back to the controller and then
			the controller does the logic and updates the flashcard

General Idea:
	- Start on homepage
		> You have four(?) options:

			- Sign-In
				> Sent to sign in page
					- back to homepage, two options:
						> Study
							- Sent to flashcards/study
						> My Cards
							- sent to flashcards/index

			- Create Account
				> Sent to register page
					- back to homepage signed in

			- Study Example Deck (Create simple example deck that is like elem. lvl)
				> study deck for user id -1 (guest id) or something else idk

			- Example Cards
				> flashcards/index for example deck

	- Flashcards index page
		> all of that users flash cards; viewable, editable, and deletable

	- Flashcards study page
		> page with square card in center that has value (front of flashcard)
			- prompts user to type meaning or reading
		> TODO: maybe add another value that is a flag for whether or not a card
						has been used the appropriate amount of times for meaning / reading
						and for correct / incorrect resets

	-->

app/views/flashcards/is_correct.html.erb
<head>
	Study Page
	<div>
		<%= link_to 'Back', root_path, class: "button is-danger" %>
	</div>
</head>
	<div id="newcard">
		<%= render partial: 'card', locals: {currcard: @currcard} %>
	</div>

app/views/flashcards/new.html.erb
<h1>New Flashcard</h1>

<%= render 'form', flashcard: @flashcard %>

<%= link_to 'Back', flashcards_path %>

app/views/flashcards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @flashcard.data %>
</p><br>

<p>
  <strong>Meaning:</strong>
  <%= @flashcard.meaning %>
</p><br>

<p>
  <strong>Reading:</strong>
  <%= @flashcard.reading %>
</p><br>

<p>
  <strong>Kunreading:</strong>
  <%= @flashcard.kunreading %>
</p><br>

<p>
  <strong>Onreading:</strong>
  <%= @flashcard.onreading %>
</p><br>

<p>
  <strong>Syn:</strong>
  <%= @flashcard.syn %>
</p><br>

<p>
  <strong>Tos:</strong>
  <%= @flashcard.tos %>
</p><br>

<p>
  <strong>Meaningmem:</strong>
  <%= @flashcard.meaningmem %>
</p><br>

<p>
  <strong>Readingmem:</strong>
  <%= @flashcard.readingmem %>
</p><br>

<p>
  <strong>Srslevel:</strong>
  <%= @flashcard.srslevel %>
</p><br>

<p>
  <strong>Cardtype:</strong>
  <%= @flashcard.cardtype %>
</p><br>

<p>
  <strong>User:</strong>
  <%= @flashcard.user_id %>
</p><br>

<p>
  <strong>CardID:</strong>
  <%= @flashcard.card_id %>
</p><br>

<%= link_to 'Edit', edit_flashcard_path(@flashcard) %> |
<%= link_to 'Back', flashcards_path %>

app/views/flashcards/study.html.erb
<head>
	Study Page
	<div>
		<%= link_to 'Back', root_path, class: "button is-danger" %>
	</div>
</head>
	<div id="newcard">
		<%= render partial: 'card', locals: {currcard: @currcard} %>
	</div>