config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users

	resources :decks do
		collection do
			get "/:id/study" => 'decks#study', as: 'study'
			get "/:id/is_correct" => 'decks#is_correct', as: 'is_correct'
		end
	end

	root 'pages#home'

	resources :flashcards do
		collection do
			get 'study'
			get 'is_correct'
		end
	end

	get "/fetch_card" => 'flashcards#fetch', as: 'fetch_card'

	controller :pages do
		get :home
		get :about
		get :contact
	end
end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :deck
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]
	require 'date'
  # GET /cards
  # GET /cards.json
  def index
    @cards = Card.all
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
		@card.cardtype = @card.created_at.to_date
		@card.save
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)
		@card.cardtype = Date.today

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def card_params
      params.require(:card).permit(:data, :meaning, :reading, :kunreading, :onreading, :syn, :tos, :meaningmem, :readingmem, :srslevel, :cardtype, :deck_id, :answer)
    end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/_form.html.erb
<%= simple_form_for(@card) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :data %>
    <%= f.input :meaning %>
    <%= f.input :reading %>
    <%= f.input :kunreading %>
    <%= f.input :onreading %>
    <%= f.input :syn %>
    <%= f.input :tos %>
    <%= f.input :meaningmem %>
    <%= f.input :readingmem %>
    <%= f.input :srslevel %>
    <%= f.input :cardtype %>
    <%= f.association :deck %>
    <%= f.input :answer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Cards</h1>

<table>
  <thead>
    <tr>
      <th>Data</th>
      <th>Meaning</th>
      <th>Reading</th>
      <th>Kunreading</th>
      <th>Onreading</th>
      <th>Syn</th>
      <th>Tos</th>
      <th>Meaningmem</th>
      <th>Readingmem</th>
      <th>Srslevel</th>
      <th>Date</th>
      <th>Deck</th>
      <th>Answer</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= card.data %></td>
        <td><%= card.meaning %></td>
        <td><%= card.reading %></td>
        <td><%= card.kunreading %></td>
        <td><%= card.onreading %></td>
        <td><%= card.syn %></td>
        <td><%= card.tos %></td>
        <td><%= card.meaningmem %></td>
        <td><%= card.readingmem %></td>
        <td><%= card.srslevel %></td>
        <td><%= card.cardtype %></td>
        <td><%= card.deck_id %></td>
        <td><%= card.answer %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Card', new_card_path %>

app/views/cards/new.html.erb
<h1>New Card</h1>

<%= render 'form', card: @card %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Data:</strong>
  <%= @card.data %>
</p>

<p>
  <strong>Meaning:</strong>
  <%= @card.meaning %>
</p>

<p>
  <strong>Reading:</strong>
  <%= @card.reading %>
</p>

<p>
  <strong>Kunreading:</strong>
  <%= @card.kunreading %>
</p>

<p>
  <strong>Onreading:</strong>
  <%= @card.onreading %>
</p>

<p>
  <strong>Syn:</strong>
  <%= @card.syn %>
</p>

<p>
  <strong>Tos:</strong>
  <%= @card.tos %>
</p>

<p>
  <strong>Meaningmem:</strong>
  <%= @card.meaningmem %>
</p>

<p>
  <strong>Readingmem:</strong>
  <%= @card.readingmem %>
</p>

<p>
  <strong>Srslevel:</strong>
  <%= @card.srslevel %>
</p>

<p>
  <strong>DateCreated:</strong>
  <%= @card.cardtype %>
</p>

<p>
  <strong>Card:</strong>
  <%= @card.id %>
</p>

<p>
  <strong>Deck:</strong>
  <%= @card.deck_id %>
</p>

<p>
  <strong>Answer:</strong>
  <%= @card.answer %>
</p>

<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>
<%= link_to 'Home', root_path, class: "button is-danger" %>