config/routes.rb
Rails.application.routes.draw do
  resources :cards
  devise_for :users

	resources :decks do
		collection do
			get "/:id/study" => 'decks#study', as: 'study'
			get "/:id/is_correct" => 'decks#is_correct', as: 'is_correct'
		end
	end

	root 'pages#home'

	resources :flashcards do
		collection do
			get 'study'
			get 'is_correct'
		end
	end

	get "/fetch_card" => 'flashcards#fetch', as: 'fetch_card'

	controller :pages do
		get :home
		get :about
		get :contact
	end
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
	has_many :cards, dependent: :destroy
	accepts_nested_attributes_for :cards
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy, :study, :is_correct]
	require 'date'
  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

	def study
		@cardindex = params[:index]
		index = @cardindex.to_i
		if (index == 0)
			@cardindex = canBeUsed(@deck, index)
		end
		#puts @deck.cards[index].srslevel
		#puts @deck.cards[index].created_at
		@currday = Date.today

		#@date = Date.today
		#@date2 = Date.today + 60
		#puts (@date2 - @date).to_i
		#puts "index: " + @cardindex
	end

	def is_correct
		index = params[:value_index].to_i
		#puts "pIndex"
		#puts params[:value_index].to_i
		#puts "size " + @deck.cards.size.to_s
		#@date = Date.today + 10
		#puts (@deck.cards[index].created_at).to_date
		#puts (@date - (@deck.cards[index].created_at).to_date).to_i

		if index < @deck.cards.size
			#canBeUsed(@deck, index)
			@deck.cards[index].answer = params[:value].to_s
			#puts params[:value]
			#puts "hello"
			#puts @deck.cards[index].answer
			#puts index
			#puts @deck.cards[index].meaning.to_s

			respond_to do |format|
	      if @deck.cards[index].answer.to_s == @deck.cards[index].meaning.to_s
					@deck.cards[index].srslevel += 1
					@deck.cards[index].cardtype = Date.today
					puts "hello"
					puts @deck.cards[index].srslevel
					@deck.save
					puts @deck.cards[index].srslevel
					puts "goodbye"
					new_index = canBeUsed(@deck, index+1)
	        format.html { redirect_to study_decks_path(@deck, :index => new_index), notice: 'Correct!' }
	      else
					puts index
					new_index = canBeUsed(@deck, index+1)
					if (@deck.cards[index].srslevel > 1)
						@deck.cards[index].srslevel = @deck.cards[index].srslevel - 1
					end
					puts @deck.cards[index].srslevel
					puts new_index
					@deck.cards[index].cardtype = Date.today
					@deck.save
	        format.html { redirect_to study_decks_path(@deck, :index => new_index), notice: 'Incorrect :(' }
	      end
	    end
		end
	end

	def srs

	end

	def canBeUsed(deck, index)
		@currday = Date.today
		#puts @deck.cards[0].cardtype
		if index >= @deck.cards.size
			return -1
		end

		dif = (@currday - Date.parse(@deck.cards[index].cardtype)).to_i
		#puts dif

		if @deck.cards[index].srslevel.to_i == 1
			return index
		elseif dif == 0 && @deck.cards[index].srslevel.to_i != 1
			for ind in (index.to_i...@deck.cards.length)
				if @deck.cards[ind].srslevel.to_i == 1
#					puts "why"
					return ind
				else
					return -1
				end
			end
		end

		if dif != 0 && dif.even? && @deck.cards[index].srslevel.to_i == 2
			#puts "pls"
			return index
		elseif dif != 0 && dif.even? && @deck.cards[index].srslevel.to_i != 2
			for ind in (index.to_i...@deck.cards.length)
				if @deck.cards[ind].srslevel.to_i == 2
#					puts "does"
					return ind
				else
					return -1
				end
			end
		end
#		puts "dd"

		if dif != 0 && (dif % 4 == 0) && @deck.cards[index].srslevel.to_i == 3
			return index
		elseif dif != 0 && (dif % 4 == 0) && @deck.cards[index].srslevel.to_i != 3
			for ind in (index.to_i...@deck.cards.length)
				if @deck.cards[ind].srslevel.to_i == 3
#						puts "this"
					return ind
				else
					return -1
				end
			end
		end

		if dif != 0 && (dif % 9 == 0) && @deck.cards[index].srslevel.to_i == 4
			return index
		elseif dif != 0 && (dif % 9 == 0) && @deck.cards[index].srslevel.to_i != 4
			for ind in (index.to_i...@deck.cards.length)
				if @deck.cards[ind].srslevel.to_i == 4
#						puts "happen"
					return ind
				else
					return -1
				end
			end
		end

		if @deck.cards[index].srslevel.to_i == 5
			return -1
		end

		canBeUsed(deck, index+1)
	end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def deck_params
      params.require(:deck).permit(:title, :category, :user_id, :cardcount)
    end
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/decks/_form.html.erb
<%= simple_form_for(@deck) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :category %>
    <%= f.association :user %>
    <%= f.input :cardcount %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<h1>Editing <%= @deck.title %></h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Show', @deck %> |
<%= link_to 'Back', decks_path %>

app/views/decks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Decks</h1>

<table class="table is-striped is-hoverable table center">
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>User</th>
      <th>Cardcount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.title %></td>
        <td><%= deck.category %></td>
        <td><%= deck.user_id %></td>
        <td><%= deck.cards.all.size %></td>
				<td><%= link_to 'Study', study_decks_path(deck, :index => 0) %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>
<%= link_to 'Home', "home", class: "button is-danger" %>

app/views/decks/new.html.erb
<h1>New Deck</h1>

<%= render 'form', deck: @deck %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @deck.title %>
</p>

<p>
  <strong>Category:</strong>
  <%= @deck.category %>
</p>

<p>
  <strong>User:</strong>
  <%= @deck.user_id %>
</p>

<p>
  <strong>Cardcount:</strong>
  <%= @deck.cardcount %>
</p>

<h1>Cards</h1>

<table class="table is-striped is-hoverable table center">
  <thead>
    <tr>
      <th>Data</th>
      <th>Meaning</th>
      <th>Reading</th>
      <th>Kunreading</th>
      <th>Onreading</th>
      <th>Syn</th>
      <th>Tos</th>
      <th>Meaningmem</th>
      <th>Readingmem</th>
      <th>Srslevel</th>
      <th>Cardtype</th>
      <th>Deck</th>
      <th>Answer</th>
			<th>Card_id</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deck.cards.each do |card| %>
      <tr>
        <td><%= card.data %></td>
        <td><%= card.meaning %></td>
        <td><%= card.reading %></td>
        <td><%= card.kunreading %></td>
        <td><%= card.onreading %></td>
        <td><%= card.syn %></td>
        <td><%= card.tos %></td>
        <td><%= card.meaningmem %></td>
        <td><%= card.readingmem %></td>
        <td><%= card.srslevel %></td>
        <td><%= card.cardtype %></td>
        <td><%= card.deck_id %></td>
        <td><%= card.answer %></td>
				<td><%= card.id %></td>
        <td><%= link_to 'Show', card %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'New Card', new_card_path %>
<%= link_to 'Edit', edit_deck_path(@deck) %> |
<%= link_to 'Back', decks_path %>
<%= link_to 'Home', root_path, class: "button is-danger" %>

app/views/decks/study.html.erb
<% index = @cardindex %>
<% if index.to_i != -1 && index.to_i < @deck.cards.size %>
<p><%= @deck.title %></p>
<p>Index: <%= @cardindex %></p>
<% puts index %>
<p>hello:<%= @deck.cards[0].srslevel %></p>
	<p><%= @deck.cards[@cardindex.to_i].data %></p>
	<p><%= @deck.cards[@cardindex.to_i].meaning %></p><br><br>

	<%= form_with url: is_correct_decks_path(@deck, :index => index), local: true, method: 'get' do |f| %>
		<%= f.text_field :value, :class => "input", placeholder: "Meaning" %>
		<%= f.text_field :value_index, :class => "input", value: index %>
		<p><br></p>
		<%= f.submit "Check", :class => "button is-primary" %>
	<% end %>
<% else %>
	<p>No More Cards Ready</p>
	<%= link_to 'Home', root_path, class: "button is-danger" %>
<% end %>